export const communitiesData = [
  {
    id: 'monument-at-reverence',
    name: 'Monument at Reverence',
    builder: 'Pulte Homes',
    village: 'Reverence',
    type: 'Townhomes',
    priceRange: 'Starting from the $500s',
    sqftRange: '1,654 - 1,869 sq ft',
    beds: '3-4',
    baths: '2.5-3',
    description:
      "Two-story townhomes in Summerlin's northernmost guard-gated community",
    features: ['24-hour guard-gated', 'Energy-efficient', 'Modern floor plans'],
    amenities: [
      'Reverence Park',
      'Community pool',
      'Fitness center',
      'Walking trails',
    ],
    highlights: ['Featured Pulte Community', 'Dr. Jan Duffy On-Site Agent'],
  },
  {
    id: 'summerlin-west',
    name: 'Summerlin West',
    builder: 'Multiple Builders',
    village: 'Summerlin West',
    type: 'Single Family Homes',
    priceRange: '$400s - $1M+',
    sqftRange: '1,200 - 4,000+ sq ft',
    beds: '2-6',
    baths: '2-5',
    description:
      'Established neighborhood with mature landscaping and mountain views',
    features: ['Mature trees', 'Mountain views', 'Established community'],
    amenities: ['Parks', 'Trails', 'Shopping centers', 'Schools'],
    highlights: ['Established Community', 'Mountain Views'],
  },
  {
    id: 'downtown-summerlin',
    name: 'Downtown Summerlin',
    builder: 'Multiple Builders',
    village: 'Downtown Summerlin',
    type: 'Mixed Use',
    priceRange: '$300s - $800s',
    sqftRange: '800 - 3,000+ sq ft',
    beds: '1-4',
    baths: '1-3.5',
    description:
      'Urban living with shopping, dining, and entertainment at your doorstep',
    features: ['Walkable', 'Urban amenities', 'Mixed-use development'],
    amenities: ['Shopping', 'Dining', 'Entertainment', 'Office space'],
    highlights: ['Walkable Community', 'Urban Amenities'],
  },
  {
    id: 'the-ridges',
    name: 'The Ridges',
    builder: 'Multiple Builders',
    village: 'The Ridges',
    type: 'Luxury Homes',
    priceRange: '$800s - $3M+',
    sqftRange: '2,500 - 8,000+ sq ft',
    beds: '3-6',
    baths: '3-7',
    description: 'Luxury homes with golf course and mountain views',
    features: ['Golf course views', 'Mountain views', 'Luxury finishes'],
    amenities: ['Golf course', 'Country club', 'Spa', 'Fine dining'],
    highlights: ['Luxury Community', 'Golf Course Views'],
  },
  {
    id: 'trails',
    name: 'The Trails',
    builder: 'Multiple Builders',
    village: 'The Trails',
    type: 'Single Family Homes',
    priceRange: '$500s - $1.2M',
    sqftRange: '1,800 - 4,500 sq ft',
    beds: '3-5',
    baths: '2.5-4.5',
    description:
      'Family-friendly community with parks and recreational facilities',
    features: ['Family-oriented', 'Parks', 'Recreation facilities'],
    amenities: ['Community pools', 'Parks', 'Playgrounds', 'Sports courts'],
    highlights: ['Family-Friendly', 'Recreation Facilities'],
  },
  {
    id: 'summerlin',
    name: 'Summerlin',
    builder: 'Multiple Builders',
    village: 'Various',
    type: 'Mixed',
    priceRange: '$300s - $3M+',
    sqftRange: '800 - 8,000+ sq ft',
    beds: '1-6',
    baths: '1-7',
    description: 'Master-planned community with diverse housing options',
    features: ['Master-planned', 'Diverse options', 'Award-winning'],
    amenities: [
      'Golf courses',
      'Parks',
      'Shopping',
      'Schools',
      'Entertainment',
    ],
    highlights: ['Master-Planned Community', 'Award-Winning'],
  },
]

export const neighborhoodsData = [
  {
    id: 'reverence',
    name: 'Reverence',
    description:
      "Summerlin's northernmost village featuring guard-gated communities and mountain views",
    communities: ['Monument at Reverence'],
    highlights: ['Guard-gated', 'Mountain views', 'New construction'],
  },
  {
    id: 'summerlin-west',
    name: 'Summerlin West',
    description:
      'Established neighborhood with mature landscaping and convenient amenities',
    communities: ['Summerlin West', 'Various subdivisions'],
    highlights: ['Established', 'Mature trees', 'Convenient location'],
  },
  {
    id: 'downtown-summerlin',
    name: 'Downtown Summerlin',
    description:
      'Urban core with shopping, dining, entertainment, and mixed-use development',
    communities: ['Downtown Summerlin', 'Mixed-use developments'],
    highlights: ['Urban living', 'Walkable', 'Entertainment district'],
  },
  {
    id: 'the-ridges',
    name: 'The Ridges',
    description:
      'Luxury community with golf course views and high-end amenities',
    communities: ['The Ridges', 'Golf course communities'],
    highlights: ['Luxury', 'Golf course', 'High-end amenities'],
  },
  {
    id: 'the-trails',
    name: 'The Trails',
    description:
      'Family-oriented community with parks and recreational facilities',
    communities: ['The Trails', 'Family subdivisions'],
    highlights: ['Family-friendly', 'Parks', 'Recreation'],
  },
]

export const relocationData = {
  cities: [
    {
      id: 'seattle',
      name: 'Seattle',
      state: 'Washington',
      description: 'Tech hub with vibrant culture and outdoor recreation',
      highlights: [
        'Tech industry',
        'Outdoor recreation',
        'Cultural attractions',
      ],
      averageHomePrice: '$800,000',
      population: '750,000',
    },
    {
      id: 'los-angeles',
      name: 'Los Angeles',
      state: 'California',
      description: 'Entertainment capital with diverse neighborhoods',
      highlights: ['Entertainment industry', 'Diverse culture', 'Beach access'],
      averageHomePrice: '$900,000',
      population: '4,000,000',
    },
    {
      id: 'san-francisco',
      name: 'San Francisco',
      state: 'California',
      description: 'Tech center with iconic landmarks and cultural diversity',
      highlights: ['Tech industry', 'Iconic landmarks', 'Cultural diversity'],
      averageHomePrice: '$1,200,000',
      population: '875,000',
    },
    {
      id: 'new-york',
      name: 'New York',
      state: 'New York',
      description: 'The city that never sleeps with endless opportunities',
      highlights: [
        'Financial center',
        'Cultural attractions',
        'Diverse neighborhoods',
      ],
      averageHomePrice: '$700,000',
      population: '8,500,000',
    },
    {
      id: 'chicago',
      name: 'Chicago',
      state: 'Illinois',
      description: 'Midwest metropolis with architecture and culture',
      highlights: ['Architecture', 'Cultural attractions', 'Sports teams'],
      averageHomePrice: '$300,000',
      population: '2,700,000',
    },
    {
      id: 'phoenix',
      name: 'Phoenix',
      state: 'Arizona',
      description: 'Desert city with growing economy and outdoor recreation',
      highlights: [
        'Growing economy',
        'Outdoor recreation',
        'Affordable living',
      ],
      averageHomePrice: '$400,000',
      population: '1,600,000',
    },
  ],
  benefits: [
    'No state income tax',
    'Lower cost of living',
    'Growing job market',
    'Outdoor recreation',
    'Entertainment options',
    'Quality schools',
    'Modern infrastructure',
    'Business-friendly environment',
  ],
}

export const resourcesData = {
  blog: [
    {
      id: 'summerlin-guide',
      title: 'Complete Guide to Living in Summerlin',
      excerpt:
        "Everything you need to know about Summerlin's neighborhoods, amenities, and lifestyle",
      category: 'Community Guide',
      readTime: '8 min read',
      publishedAt: '2024-01-15',
    },
    {
      id: 'new-construction-tips',
      title: 'Tips for Buying New Construction Homes',
      excerpt:
        'Expert advice on navigating the new construction process and getting the best value',
      category: 'Buying Guide',
      readTime: '6 min read',
      publishedAt: '2024-01-10',
    },
    {
      id: 'monument-reverence-review',
      title: 'Monument at Reverence: A Detailed Review',
      excerpt:
        "In-depth look at Pulte's newest community in Summerlin's Reverence village",
      category: 'Community Spotlight',
      readTime: '10 min read',
      publishedAt: '2024-01-05',
    },
  ],
  guides: [
    {
      id: 'first-time-buyer',
      title: 'First-Time Home Buyer Guide',
      description: 'Complete guide for first-time home buyers in Las Vegas',
      topics: ['Financing', 'Process', 'Tips', 'Resources'],
    },
    {
      id: 'selling-guide',
      title: 'Selling Your Home Guide',
      description: 'Expert tips for selling your home in the Las Vegas market',
      topics: ['Pricing', 'Staging', 'Marketing', 'Negotiation'],
    },
    {
      id: 'investment-guide',
      title: 'Real Estate Investment Guide',
      description: 'Guide to investing in Las Vegas real estate',
      topics: ['Market Analysis', 'ROI', 'Tax Benefits', 'Rental Properties'],
    },
  ],
}
